[package]
name = "okspiel"
version = "0.1.0"
authors = ["spieljs <spieljs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tarpc = { version = "0.24", features = ["tokio1"] }
tokio = { version = "1.0", features = ["macros"] }
iced = {version = "0.2", features = ["tokio", "glow", "glow_qr_code"]}